### ISSUE TITLE
Unit testing components with theming

### ISSUE THREAD

**Issue by alex996** [cssinjs/react-jss#184] opened 2017-12-06 22:29 UTC
Consider a simple component:

```jsx
// Comp.jsx
const Comp = (props) => <a>Text</a>
export default injectSheet(themeStyles)(Comp)
```

Then I'd like to unit test it:

```jsx
// Comp-test.js
import { shallow } from 'enzyme'
import { expect } from 'chai'

describe('<Comp /> component', () => {
  const wrapper = shallow(<Comp><i /></Comp>)

  it('should render an <a/>', () => {
    expect(wrapper.find('a')).to.have.length(1)
  })
})
```

The test would pass prior to adding reactjss theming, but after, the test suite fails to start with an error, `[undefined] Please use ThemeProvider to be able to use WithTheme`. Makes sense, but after I changed it to

```jsx
const wrapper = shallow(
  <ThemeProvider theme={theme}>
    <Comp><i /></Comp>
  </ThemeProvider>
)
```

the error is gone, the test suite starts, but the assertion fails, as if it can't find the `a` inside `Comp`. I also tried [this approach](https://github.com/styled-components/styled-components/issues/624#issuecomment-304289387), but the assertion still fails. Any ideas why?

@kof I saw your response on [StackOverflow](https://stackoverflow.com/questions/45261786/testing-react-components-that-have-jss-injected-styles-with-enzyme#answer-45264575) from July, but I wish you could elaborate on your second point. So far, my approach is to no avail.

**Comment by kof** [comment] 2017-12-06 22:45
Can you please provide a failing example on codesandbox.io ?

**Comment by alex996** [comment] 2017-12-06 23:15
@kof Gerne! [Here it is](https://codesandbox.io/s/674jknj4z). I ran this setup locally, with all deps installed, using `yarn test:watch`, and it failed with

```
 1) <Comp /> component
       should render a <a>:

      AssertionError: expected { length: 0 } to have a length of 1 but got 0
      + expected - actual

      -0
      +1
      
      at Context.<anonymous> (src/Comp-test.js:33:50)
```

**Comment by alex996** [comment] 2017-12-07 17:40
**Update**

I tried to `dive()` on the shallow wrapper, but the moment I do so, I get `Please use ThemeProvider to be able to use WithTheme`. Not sure if the theme needs to be passed with the context; I tried, but the same error persists.

**Comment by alex996** [comment] 2017-12-07 18:34
**Update**

Using that same setup, I tried more approaches with `dive()`, as well as `find()`/`first()`, but none of the cases pass, and they all end up failing with `Error: [undefined] Please use ThemeProvider to be able to use WithTheme`:

```js
// 1. dive()
expect(wrapper.dive('Comp')).to.have.length(1);
expect(wrapper.dive('Comp').find('a')).to.have.length(1);
expect(wrapper.dive().find('a')).to.have.length(1);

// 2. find() / first()
expect(wrapper.find(Comp).shallow().find('a')).to.have.length(1);
expect(wrapper.first().shallow().find('a')).to.have.length(1);
```

**Comment by iamstarkov** [comment] 2017-12-07 22:19
@alex996 yo. you need to unit test not enhanced component but original one

**Comment by iamstarkov** [comment] 2017-12-07 22:20
see this https://github.com/nordnet/nordnet-ui-kit/blob/master/docs/testing-component.md

**Comment by iamstarkov** [comment] 2017-12-07 22:21
the reasoning is that you dont want to unit test every HoC/wrapper because its a deep rabbit hole, you rather want to test only components you actually own

**Comment by alex996** [comment] 2017-12-07 22:22
@iamstarkov You mean I don't need to wrap it with `ThemeProvider`? If I don't I get `Please use ThemeProvider to be able to use WithTheme`. I tried passing `theme` directly on `Comp`, but it didn't help.

**Comment by kof** [comment] 2017-12-08 10:19
Major question you have to answer is: do you want to test just the render output or with styles?

Testing the render without styles is easy, you just render your component without the HOC. You can export it yourself or you can use `StyledComponent.InnerComponent`.

If you want to test with styles, you will have to use currently JssProvider, if theming is used then also ThemeProvider.

Here is an issue you probably want to follow #93

**Comment by alex996** [comment] 2017-12-08 21:05
@kof Thanks, I got the first point, but what about testing with styles? Tried your approach with `JssProvider` and `ThemeProvider`, but it doesn't allow to traverse the children of the component, e.g. assert classes. Same thing with `SheetsRegistryProvider`, as you suggested [here](https://github.com/cssinjs/react-jss/issues/93#issuecomment-312004965). Can you give an example on how to use it? (Would be an invaluable addition to the docs as well!)

My case is complicated by the fact that we're transitioning from a CSS-only setup, so now some styles are in JSS, while most are still imported through CSS files, hence I'm looking for a way to leverage both with testing.

**Comment by kof** [comment] 2017-12-08 22:25
Closing this, seems like a duplicate of #93. You guys should collaborate on testing with styles or wait until I get time for it. I can't answer non-specific questions without examples on playground, because I don't see your code.

**Closed by kof** 2017-12-08 22:25 UTC

**Comment by kof** [comment] 2017-12-08 22:26
Feel free to reach out to @wzrdzl as he is working on something for this.
