### ISSUE TITLE
Context from JssProvider doesn't get consumed when shallow rendering.

### ISSUE THREAD

**Issue by stellarhoof** [cssinjs/react-jss#242] opened 2018-05-03 18:55 UTC
With a fresh `create-react-app@next`, replace index file with:

```javascript
import React from "react";
import ReactDOM from "react-dom";
import injectSheet, { JssProvider } from "react-jss";

const generator = (rule, sheet) => "StaticClassName"

const styles = { div: { background: "red" } };

export const App = injectSheet(styles)(({ classes }) => {
  return (
    <JssProvider generateClassName={generator}>
      <div className={classes.div}> This is a div </div>
    </JssProvider>
  );
});

ReactDOM.render(<App />, document.getElementById("root"));
```

Then `yarn start` and you'll see that the class name for the rendered component hasn't changed.

However, it behaves well outside `injectSheet`:

```javascript
import React from "react";
import ReactDOM from "react-dom";
import injectSheet, { JssProvider } from "react-jss";

const generator = (rule, sheet) => "StaticClassName";

const styles = { div: { background: "red" } };

const Wrapped = injectSheet(styles)(({ classes }) => {
  return <div className={classes.div}> This is a div </div>;
});

export const App = (
  <JssProvider generateClassName={generator}>
    <Wrapped />
  </JssProvider>
);

ReactDOM.render(<App />, document.getElementById("root"));
```

**Comment by stellarhoof** [comment] 2018-05-03 21:18
Upon further investigation, the problem seems to be that there is a global JssProvider which effectively acts as a singleton. Using the second example in the post (the one that supposedly works well). This test fails to change the class names:

```javascript
import TestRenderer from "react-test-renderer";
import ShallowRenderer from "react-test-renderer/shallow";
import ReactDOMServer from "react-dom/server";
import { App } from "./index";

it("react-test-renderer/shallow", () => {
  const shallowRender = new ShallowRenderer();
  shallowRender.render(App);
  console.log(ReactDOMServer.renderToString(shallowRender.getRenderOutput()));
});

it("react-test-renderer", () => {
  console.log(TestRenderer.create(App).toJSON());
});
```

Whereas this one does:
```javascript
import TestRenderer from "react-test-renderer";
import ShallowRenderer from "react-test-renderer/shallow";
import ReactDOMServer from "react-dom/server";
import { App } from "./index";

it("react-test-renderer", () => {
  console.log(TestRenderer.create(App).toJSON());
});

it("react-test-renderer/shallow", () => {
  const shallowRender = new ShallowRenderer();
  shallowRender.render(App);
  console.log(ReactDOMServer.renderToString(shallowRender.getRenderOutput()));
});
```

Notice the second test has the order switched, so the first test now runs second.

It seems the semantics of shallow rendering interferes with the instantiation process of `JssProvider`.

**Comment by HenriBeck** [comment] 2018-05-03 22:53
In your first example, it doesn't work because the HoC isn't inside the JssProvider. The HoC needs to be a child of the JssProvider for context to work, so your examples in your post are actually working the way they should.

About the failing tests, which App component are you actually using for the test? The first or second one from your post?

**Comment by stellarhoof** [comment] 2018-05-03 22:56
The second component. When you refer to context, is it this https://reactjs.org/docs/context.html specifically?

**Comment by HenriBeck** [comment] 2018-05-03 22:59
Yes.

The vDOM in your first example will look something like this:
```jsx
<App>
  <Jss(Component)>
    <Component>
      <JssProvider>
        <div />
      </JssProvider>
    </Component>
  </Jss(Component)>
</App>
```

As you can see the actual `injectSheet` component is not a child of the JssProvider, which means it doesn't use it props.

**Comment by HenriBeck** [comment] 2018-05-03 23:01
I think the problem with the tests, is that the shallow rendering only renders one level deep, which means that only the JssProvider will get rendered and not the actual HoC.

**Comment by stellarhoof** [comment] 2018-05-03 23:13
I understand the context dynamics now. However I gotta say I don't understand the semantics of shallow rendering that well. It might very well be that the shallow rendering algorithm doesn't handle contexts as full rendering does. I have to investigate more.

**Comment by HenriBeck** [comment] 2018-05-03 23:15
I'm not exactly sure how shallow rendering deals with context but it only renders one level deep components.

**Comment by stellarhoof** [comment] 2018-05-04 01:44
It seem `JssProvider` is using the old context API https://github.com/cssinjs/react-jss/blob/b068f598d971627b5ecfb0cc14a1d967606b54bf/src/JssProvider.js#L24. The React documentation strongly advocates to use the new one (https://reactjs.org/docs/legacy-context.html#updating-context) because the old one is "fundamentally broken". Perhaps migrating to the new context API will solve this issue (or not). Regardless it's a good idea to do so.

**Comment by kof** [comment] 2018-05-04 07:50
React-JSS hasn't added new context api yet, but you can test if this is your issue by downgrading to 15.

**Comment by kof** [comment] 2018-05-04 07:51
Also I doubt it is, old context api was not removed or something.

**Comment by stellarhoof** [comment] 2018-05-04 13:15
Downgrading won't make a difference because the behavior of the old API hasn't changed (https://reactjs.org/blog/2018/03/29/react-v-16-3.html#official-context-api).

> Also I doubt it is, old context api was not removed or something.
I'm not following. If the old API behaves the same in 15 and 16 it could be the cause in those two versions as well.

**Comment by kof** [comment] 2018-05-04 13:17
I think we need a clear problem definition. Can you please create a codesandbox with a clear bug reproduction?

**Comment by stellarhoof** [comment] 2018-05-04 15:11
You're right I should've included one when I opened the issue. Here you go: https://codesandbox.io/s/oolql91vmz. Go straight to the tests.

**Comment by stellarhoof** [comment] 2018-05-04 17:01
Actually using the new context API will probably break more than it fixes. See https://github.com/airbnb/enzyme/issues/1647. At least with the current enzyme you can manually pass down context (http://airbnb.io/enzyme/docs/api/ShallowWrapper/dive.html).
The default react shallow renderer is another beast I think.

**Comment by kof** [comment] 2018-06-19 20:35
I am not sure whats going on with the context and shallow renderer, but as a workaround if you need to set a class names generator for testing, here is an example

basically before any injectSheet calls:

```js
import { jss } from "react-jss";
// Not a public api, its a workaround.
jss.generateClassName = () => "static";
```

https://codesandbox.io/s/pm18k234vj

**Comment by stellarhoof** [comment] 2018-06-20 11:49
I am not using shallow rendering any more, but I believe this issue can be closed since it seems to be a limitation of the old context API. If you notice in enzyme's docs link above, the context has to be passed manually for it to get picked up, and I don't think they support the new context API. If there's an actionable plan outta this issue is to eventually use the new API here.

**Comment by HenriBeck** [comment] 2018-06-20 13:29
I think that's a problem with enzymes shallow rendering and not react-jss itself.

**Comment by kof** [comment] 2018-06-20 13:35
@stellarhoof thanks for clarifying, I am closing this for now.

**Closed by kof** 2018-06-20 13:35 UTC
Labels: help wanted
