### ISSUE TITLE
Function values bypass plugins

### ISSUE THREAD

**Issue by jcheroske** [cssinjs/react-jss#78] opened 2017-03-20 06:24 UTC
I'm seeing that the dynamic styles are not being processed by the plugins. I've got (among others) the camelCase plugin and an important plugin installed. But my styles are looking like: 

```css
snackbarBody-0-95 {
  backgroundColor: #303030
}
```
when the style should look like:
```css
snackbarBody-0-95 {
  background-color: #303030 !important
}
```
Static styles are working fine.

**Comment by kof** [comment] 2017-03-20 08:13
Duplicate of https://github.com/cssinjs/jss/issues/441

**Closed by kof** 2017-03-20 08:13 UTC
