### ISSUE TITLE
dynamic rules not parsing properly

### ISSUE THREAD

**Issue by PolGuixe** [cssinjs/react-jss#79] opened 2017-03-21 13:45 UTC
This: 
```
  xs: {
    MsFlexPreferredSize: props => `${(props.xs/12)*100}%`,
    flexBasis: props => `${(props.xs/12)*100}%`,
    maxWidth: props =>`${(props.xs/12)*100}%`,
  },
```

is parsed into: 
```
.xs-0-15 {
  MsFlexPreferredSize: 100%;
  flexBasis: 100%;
  maxWidth: 100%;
}
```
_The whole component can be seen here: https://gist.github.com/PolGuixe/0e8da76f1a54f0d7f594c1ecd3f69345_

I've been following the documentations, still I don't why it doesn't work.

**Comment by kof** [comment] 2017-03-21 15:46
Duplicate of https://github.com/cssinjs/jss/issues/441

**Closed by kof** 2017-03-21 15:46 UTC
